# Generated by Django 3.1.5 on 2021-03-18 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snowboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snowboard',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
